---
title: HIDRA-PORT Comércio de Peças e Equipamentos Hidráulicos © 2013
timezone: UTC
collections:
  aplicacoes:
    title: Aplicacoes
    output: false
  categorias:
    title: Categorias
    output: true
  posts:
    title: Posts
    output: true
  produtos:
    title: Produtos
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: aplicacoes
  values:
    layout: page
- scope:
    path: ''
    type: categorias
  values:
    layout: categoria
- scope:
    path: ''
    type: produtos
  values:
    layout: produto
description: 'LOJA DE FÁBRICA, especializada no fornecimento de mangueiras  e conexões
  desde 2007. Fabricamos e distribuímos materiais para  manutenção e montagem industrial
  em toda a região da Baixada Santista.  Atendemos empresas dos setores metalúrgico,
  químico, siderúrgico,  de autopeças, plásticos, papeleiros, de navegação, entre
  outros.

'
baseurl: 
url: http://hidraport.com.br
permalink: :pretty/
exclude:
- gulpfile.js
- README.md
- desktop.ini
markdown: kramdown
sass:
  style: compressed
plugins:
- jekyll-coffeescript
