---
title: HIDRA-PORT Comércio de Peças e Equipamentos Hidráulicos © 2013
timezone: UTC
collections:
  aplicacoes:
    title: Aplicacoes
    output: false
  categorias:
    title: Categorias
    output: true
  posts:
    title: Posts
    output: true
  produtos:
    title: Produtos
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: aplicacoes
  values:
    layout: page
    image: 
- scope:
    path: ''
    type: categorias
  values:
    layout: categoria
    permalink: produtos/:path/
- scope:
    path: ''
    type: produtos
  values:
    layout: produto
    categoria: 
    image: 
lang: pt_BR
description: 'LOJA DE FÁBRICA, especializada no fornecimento de mangueiras  e conexões
  desde 2007. Fabricamos e distribuímos materiais para  manutenção e montagem industrial
  em toda a região da Baixada Santista.  Atendemos empresas dos setores metalúrgico,
  químico, siderúrgico,  de autopeças, plásticos, papeleiros, de navegação, entre
  outros.

'
baseurl: 
url: http://hidraport.com.br
endereco:
- Av. Rangel Pestana 54, Vila Mathias - Santos-SP
telefones:
- label: "(13) 3223-6576"
  number: "+551332236576"
- label: "(13) 3223-9652"
  number: "+551332239652"
- label: "(13) 3223-2997"
  number: "+551332232997"
- label: 'Fax.: (13) 3235-8665'
  number: "+551332358665"
- label: 'ID: 7*43245'
whatsapp:
  label: 'Whatsapp: (13) 9 9693-8470'
  number: '5513996938470'
email: hidraport@hidraport.com.br
facebook: https://www.facebook.com/Hidra-port-Mangueiras-e-Conex%C3%B5es-239814696459784/
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- desktop.ini
markdown: kramdown
sass:
  style: compressed
permalink: ":pretty/"
plugins:
- jekyll-sitemap
