title: HIDRA-PORT Comércio de Peças e Equipamentos Hidráulicos © 2013
description: >
  LOJA DE FÁBRICA, especializada no fornecimento de mangueiras 
  e conexões desde 2007. Fabricamos e distribuímos materiais para 
  manutenção e montagem industrial em toda a região da Baixada Santista. 
  Atendemos empresas dos setores metalúrgico, químico, siderúrgico, 
  de autopeças, plásticos, papeleiros, de navegação, entre outros.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hidraport.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-coffeescript

collections:
  categorias:
    output: true

defaults:
  - scope:
      path: ""
      type: categorias
    values:
      layout: produto
      permalink: produtos/:path/
